sudo: false
matrix:
  fast_finish: true
  include:
    - python: "3.5"
      env: TOXENV=lint
    - python: "3.6"
      env: TOXENV=lint
install: pip install pylint gitpython
language: python
script: pylint configurator.py