sudo: false
matrix:
  fast_finish: true
  include:
    - python: "3.4"
      env: TOXENV=lint
    - python: "3.5"
      env: TOXENV=lint
install: pip install pylint
language: python
script: pylint configurator.py